name: trainly
description: Rozkład jazdy kolei w Polsce
publish_to: 'none'

version: 2.0.0-beta.1+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.4.28
  provider: ^6.1.1
  intl: ^0.20.3
  geolocator: ^13.0.2
  package_info_plus: ^8.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/branding/kolejka_icon.png"
  adaptive_icon_foreground: "assets/branding/kolejka_icon_foreground.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
